server:
  port: 8082

spring:
  profiles:
    active: dev


## 高德地图的key配置
gaode:
  userKey: fa7bf16deb815e729283e0e8407a73a7

#job
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      appname: xxl-job-executor
#      ip:
#      port: 9999
#      logpath: D:\jobLogpath
#      logretentiondays: -1
#xml:
#  path: E:\workspace\dls\dls-api\src\main\java\com\rnstec\api\util

#xxl:
#  job:
#    admin:
#      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    ### xxl-job executor address
#    executor:
#      appname: mktcenter
#      ip:
#      port: 9999
#      ### xxl-job log path
#      logpath: /data/applogs/xxl-job/jobhandler
#      ### xxl-job log retention days
#      logretentiondays: -1
#    ### xxl-job, access token
#    accessToken: