spring:
  kafka:
    bootstrap-servers: 113.89.13.63:9092
    consumer:
      group-id: consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100s
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.80:9300
      cluster-name: my-application
  redis:
#    host: 115.159.71.171
    host: 47.113.105.209
    port: 6379
    database: 8
    password: CyouTest!Q@W1q2w

api:
  server:
    url: http://113.89.13.63:8000




#job
#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      appname: xxl-job-executor
#      ip:
#      port: 9999
#      logpath: D:\jobLogpath
#      logretentiondays: -1
#xml:
#  path: E:\workspace\dls\dls-api\src\main\java\com\rnstec\api\util

#xxl:
#  job:
#    admin:
#      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    ### xxl-job executor address
#    executor:
#      appname: mktcenter
#      ip:
#      port: 9999
#      ### xxl-job log path
#      logpath: /data/applogs/xxl-job/jobhandler
#      ### xxl-job log retention days
#      logretentiondays: -1
#    ### xxl-job, access token
#    accessToken: