create table permission
(
    id          BIGINT(19) auto_increment comment 'ID'
        primary key,
    alias       VARCHAR(255) null comment '别名',
    create_time DATETIME(19) null comment '创建日期',
    name        VARCHAR(255) null comment '名称',
    pid         INT(10)      not null comment '上级权限'
);

INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (1, '超级管理员', '2018-12-03 12:27:48', 'ADMIN', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (2, '用户管理', '2018-12-03 12:28:19', 'USER_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (3, '用户查询', '2018-12-03 12:31:35', 'USER_SELECT', 2);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (4, '用户创建', '2018-12-03 12:31:35', 'USER_CREATE', 2);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (5, '用户编辑', '2018-12-03 12:31:35', 'USER_EDIT', 2);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (6, '用户删除', '2018-12-03 12:31:35', 'USER_DELETE', 2);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (7, '角色管理', '2018-12-03 12:28:19', 'ROLES_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (8, '角色查询', '2018-12-03 12:31:35', 'ROLES_SELECT', 7);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (10, '角色创建', '2018-12-09 20:10:16', 'ROLES_CREATE', 7);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (11, '角色编辑', '2018-12-09 20:10:42', 'ROLES_EDIT', 7);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (12, '角色删除', '2018-12-09 20:11:07', 'ROLES_DELETE', 7);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (13, '权限管理', '2018-12-09 20:11:37', 'PERMISSION_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (14, '权限查询', '2018-12-09 20:11:55', 'PERMISSION_SELECT', 13);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (15, '权限创建', '2018-12-09 20:14:10', 'PERMISSION_CREATE', 13);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (16, '权限编辑', '2018-12-09 20:15:44', 'PERMISSION_EDIT', 13);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (17, '权限删除', '2018-12-09 20:15:59', 'PERMISSION_DELETE', 13);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (18, '缓存管理', '2018-12-17 13:53:25', 'REDIS_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (19, '新增缓存', '2018-12-17 13:53:44', 'REDIS_CREATE', 18);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (20, '缓存查询', '2018-12-17 13:54:07', 'REDIS_SELECT', 18);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (21, '缓存编辑', '2018-12-17 13:54:26', 'REDIS_EDIT', 18);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (22, '缓存删除', '2018-12-17 13:55:04', 'REDIS_DELETE', 18);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (23, '图床管理', '2018-12-27 20:31:49', 'PICTURE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (24, '查询图片', '2018-12-27 20:32:04', 'PICTURE_SELECT', 23);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (25, '上传图片', '2018-12-27 20:32:24', 'PICTURE_UPLOAD', 23);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (26, '删除图片', '2018-12-27 20:32:45', 'PICTURE_DELETE', 23);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (29, '菜单管理', '2018-12-28 17:34:31', 'MENU_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (30, '菜单查询', '2018-12-28 17:34:41', 'MENU_SELECT', 29);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (31, '菜单创建', '2018-12-28 17:34:52', 'MENU_CREATE', 29);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (32, '菜单编辑', '2018-12-28 17:35:20', 'MENU_EDIT', 29);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (33, '菜单删除', '2018-12-28 17:35:29', 'MENU_DELETE', 29);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (35, '定时任务管理', '2019-01-08 14:59:57', 'JOB_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (36, '任务查询', '2019-01-08 15:00:09', 'JOB_SELECT', 35);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (37, '任务创建', '2019-01-08 15:00:20', 'JOB_CREATE', 35);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (38, '任务编辑', '2019-01-08 15:00:33', 'JOB_EDIT', 35);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (39, '任务删除', '2019-01-08 15:01:13', 'JOB_DELETE', 35);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (40, '部门管理', '2019-03-29 17:06:55', 'DEPT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (41, '部门查询', '2019-03-29 17:07:09', 'DEPT_SELECT', 40);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (42, '部门创建', '2019-03-29 17:07:29', 'DEPT_CREATE', 40);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (43, '部门编辑', '2019-03-29 17:07:52', 'DEPT_EDIT', 40);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (44, '部门删除', '2019-03-29 17:08:14', 'DEPT_DELETE', 40);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (45, '岗位管理', '2019-03-29 17:08:52', 'USERJOB_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (46, '岗位查询', '2019-03-29 17:10:27', 'USERJOB_SELECT', 45);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (47, '岗位创建', '2019-03-29 17:10:55', 'USERJOB_CREATE', 45);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (48, '岗位编辑', '2019-03-29 17:11:08', 'USERJOB_EDIT', 45);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (49, '岗位删除', '2019-03-29 17:11:19', 'USERJOB_DELETE', 45);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (50, '字典管理', '2019-04-10 16:24:51', 'DICT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (51, '字典查询', '2019-04-10 16:25:16', 'DICT_SELECT', 50);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (52, '字典创建', '2019-04-10 16:25:29', 'DICT_CREATE', 50);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (53, '字典编辑', '2019-04-10 16:27:19', 'DICT_EDIT', 50);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (54, '字典删除', '2019-04-10 16:27:30', 'DICT_DELETE', 50);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (57, '日报管理', '2019-04-25 20:33:31', 'REPORT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (58, '车辆列表', null, 'BIKE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (59, '新增车辆', null, 'BIKE_CREATE', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (60, '车辆删除', null, 'BIKE_DELETE', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (61, '车辆编辑', null, 'BIKE_EDIT', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (62, '必到点管理', null, 'POINT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (63, '必到点修改', null, 'POINT_EDIT', 62);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (64, '必到点删除', null, 'POINT_DELETE', 62);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (65, '虚拟桩管理', null, 'VIRTUALPILE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (66, '虚拟桩新增', null, 'VIRTUALPILE_CREATE', 65);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (67, '虚拟桩删除', null, 'VIRTUALPILE_DELETE', 65);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (68, '虚拟桩修改', null, 'VIRTUALPILE__EDIT', 65);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (69, '限行围栏管理', null, 'FENCE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (70, '围栏新增', null, 'FENCE_CREATE', 69);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (71, '围栏编辑', null, 'FENCE_EDIT', 69);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (72, '添加必到点', null, 'POINT_CREATE', 62);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (73, '围栏删除', null, 'FENCE_DELETE', 69);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (74, '查询必到点', null, 'POINT_SELECT', 62);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (75, '订单管理', null, 'ORDER_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (76, '订单删除', null, 'ORDER_DELETE', 75);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (77, '订单编辑', null, 'ORDER_EDIT', 75);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (78, '订单创建', null, 'ORDER_CREATE', 75);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (79, '车辆授权', null, 'LICENSE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (80, '车辆授权编辑', null, 'LICENSE_EDIT', 79);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (81, '车辆授权删除', null, 'LICENSE_DELETE', 79);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (82, '车辆授权新增', null, 'LICENSE_CREATE', 79);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (83, '车锁管理', null, 'LOCK_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (84, '车锁编辑', null, 'LOCK_EDIT', 83);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (85, '车锁删除', null, 'LOCK_DELETE', 83);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (86, '车锁创建', null, 'LOCK_CREATE', 83);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (87, '轮播图管理', null, 'SHUFFLING_FIGURE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (88, '轮播图查询', null, 'SHUFFLING_FIGURE_SELECT', 87);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (89, '轮播图创建', null, 'SHUFFLING_FIGURE_CREATE', 87);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (90, '轮播图修改', null, 'SHUFFLING_FIGURE_EDIT', 87);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (91, '轮播图删除', null, 'SHUFFLING_FIGURE_DELETE', 87);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (92, '常见问题', null, 'PROBLEM_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (93, '问题新增', null, 'PROBLEM_CREATE', 92);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (94, '问题删除', null, 'PROBLEM_DELETE', 92);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (95, '问题编辑', null, 'PROBLEM_EDIT', 92);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (96, '新闻公告', null, 'NEWS_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (97, '新闻新增', null, 'NEWS_CREATE', 96);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (98, '新闻删除', null, 'NEWS_DELETE', 96);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (99, '新闻编辑', null, 'NEWS_EDIT', 96);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (100, '题库管理', null, 'QUESTION_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (101, '问题新增', null, 'QUESTION_CREATE', 100);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (102, '问题删除', null, 'QUESTION_DELETE', 100);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (103, '问题编辑', null, 'QUESTION_EDIT', 100);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (104, '调查问卷', null, 'QUESTIONNAIRES_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (105, '问卷创建', null, 'QUESTIONNAIRES_CREATE', 104);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (106, '问卷删除', null, 'QUESTIONNAIRES_DELETE', 104);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (107, '问卷编辑', null, 'QUESTIONNAIRES_EDIT', 104);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (108, '内部消息上报', null, 'INTERNAL_INFORMATION_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (109, '内部消息上报列表', null, 'INTERNAL_INFORMATION_SELECT', 108);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (110, '内部消息上报详细', null, 'INTERNAL_INFORMATION_DETAIL', 108);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (111, '违法举报', null, 'ILLEGAL_REPORT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (112, '违法举报列表', null, 'ILLEGAL_REPORT_SELECT', 111);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (113, '违法举报详细', null, 'ILLEGAL_REPORT_DETAIL', 111);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (114, '物品类别管理', null, 'ARTICLE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (115, '物品类别列表', null, 'ARTICLE_SELECT', 114);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (116, '新增物品', null, 'ARTICLE_CREATE', 114);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (117, '修改物品', null, 'ARTICLE_EDIT', 114);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (118, '删除物品', null, 'ARTICLE_DELETE', 114);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (119, '物品数量管理', null, 'ARTICLE_NUMBER_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (120, '物品数量查询', null, 'ARTICLE_NUMBER_SELECT', 119);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (121, '物品数量添加', null, 'ARTICLE_NUMBER_CREATE', 119);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (122, '物品数量修改', null, 'ARTICLE_NUMBER_EDIT', 119);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (123, '物品数量删除', null, 'ARTICLE_NUMBER_DELETE', 119);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (124, '满意度查看', null, 'EVALUATIONALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (125, '充值管理', null, 'TOP_UP_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (126, '充值查询', null, 'TOP_UP_SELECT', 125);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (127, '充值添加', null, 'TOP_UP_CREATE', 125);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (128, '充值修改', null, 'TOP_UP_EDIT', 125);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (129, '充值删除', null, 'TOP_UP_DELETE', 125);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (130, '物品借还记录', null, 'BORROWING_RETURNING_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (131, '小程序模块分配管理', null, 'APPMODULE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (132, '小程序模块权限编辑', null, 'APPMODULE_EDIT', 131);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (133, '小程序模块权限创建', null, 'APPMODULE_CREATE', 131);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (134, '第三方系统使用', null, 'OTHER_SYSTEM', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (135, '辖区配置管理', null, 'JURISDICTION_CONFIGURATION_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (136, '辖区配置查询', null, 'JURISDICTION_CONFIGURATION_SELECT', 135);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (137, '辖区配置操作', null, 'JURISDICTION_CONFIGURATION_OPERATION', 135);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (138, '图标管理', null, 'ICON_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (139, '图标创建', null, 'ICON_CREATE', 138);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (140, '图标编辑', null, 'ICON_EDIT', 138);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (141, '图标删除', null, 'ICON_DELETE', 138);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (142, '其他参考点管理', null, 'REFERENCEPOINT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (143, '参考点创建', null, 'REFERENCEPOINT_CREATE', 142);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (144, '参考点编辑', null, 'REFERENCEPOINT_EDIT', 142);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (145, '参考点删除', null, 'REFERENCEPOINT_DELETE', 142);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (146, '小程序人员管理', null, 'MAUSER_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (147, '查询权限', null, 'MAUSER_SELECT', 146);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (148, '编辑权限', null, 'MAUSER_EDIT', 146);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (149, '删除权限', null, 'MAUSER_DELETE', 146);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (150, '关于我们', null, 'ABOUTUS_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (151, '关于我们新增', null, 'ABOUTUS_CREATE', 150);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (152, '关于我们编辑', null, 'ABOUTUS_EDIT', 150);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (153, '关于我们删除', null, 'ABOUTUS_DELETE', 150);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (154, '智能巡更任务模板管理', null, 'TASKTEMPLATE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (155, '创建任务模板', null, 'TASKTEMPLATE_CREATE', 154);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (156, '编辑任务模板', null, 'TASKTEMPLATE_EDIT', 154);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (157, '删除任务模板', null, 'TASKTEMPLATE_DELETE', 154);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (158, '智能巡更任务审核管理', null, 'TASKAPPROVAL_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (159, '审核任务', null, 'TASKAPPROVAL_EDIT', 158);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (160, '车辆图标管理', null, 'BIKEICON_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (161, '删除', null, 'BIKEICON_DELETE', 160);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (162, '创建', null, 'BIKEICON_CREATE', 160);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (163, '编辑', null, 'BIKEICON_EDIT', 160);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (164, '车辆监控', null, 'BIKE_MONITOR', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (165, '车辆警告管理', null, 'BIKE_WARN_ALL', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (166, '车辆警告查询', null, 'BIKE_WARN_SELECT', 58);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (167, '统计管理', null, 'STATIC_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (168, '统计查询', null, 'STATIC_SELECT', 167);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (169, '测试123', null, 'test1123', 150);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (171, '123', null, 'test123', 169);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (173, '房屋出租', null, 'HOUSING_RENTAL_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (174, '测试0002', null, 'test_002', 2);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (175, '出租人义务告知', null, 'INFORM_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (176, '创建告知', null, 'INFORM_CREATE', 175);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (177, '删除告知', null, 'INFORM_DELETE', 175);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (178, '编辑告知', null, 'INFORM_EDIT', 175);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (179, '视频管理', null, 'VIDEO_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (180, '视频查询', null, 'VIDEO_SELECT', 179);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (181, '视频创建', null, 'VIDEO_CREATE', 179);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (182, '视频编辑', null, 'VIDEO_EDIT', 179);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (183, '视频删除', null, 'VIDEO_DELETE', 179);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (184, '小游戏管理', null, 'GAME_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (185, '小游戏查询', null, 'GAME_SELECT', 184);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (186, '小游戏创建', null, 'GAME_CREATE', 184);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (187, '小游戏修改', null, 'GAME_EDIT', 184);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (188, '小游戏删除', null, 'GAME_DELETE', 184);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (189, '公众号管理', null, 'PUBLICACCOUNT_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (190, '同步公众号文章', null, 'NEWS_PUBLIC_ACCOUNT_ADD', 96);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (191, '居委会管理', null, 'COMITE_ALL', 0);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (192, '居委会新增', null, 'COMITE_CREATE', 191);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (193, '居委会查询', null, 'COMITE_SELECT', 191);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (194, '居委会编辑', null, 'COMITE_EDIT', 191);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (195, '居委会删除', null, 'COMITE_DELETE', 191);
INSERT INTO cyoubike.permission (id, alias, create_time, name, pid) VALUES (196, '口罩预约管理', null, 'RESERVE_MASK_ALL', 0);